import AcmeLogo from '@/app/ui/acme-logo';
import LoginForm from '@/app/ui/login-form';
import { Metadata } from 'next';


export const metadata: Metadata = {
    title: "login",
}

export default function LoginPage() {
    return (
        <main className="flex items-center justify-center md:h-screen">
            <div className="relative mx-auto flex w-full max-w-[400px] flex-col space-y-2.5 p-4 md:-mt-32">
                <div className="flex h-20 w-full items-end rounded-lg bg-blue-500 p-3 md:h-36">
                    <div className="w-32 text-white md:w-36">
                        <AcmeLogo />
                    </div>
                </div>
                <LoginForm />
            </div>
        </main>
    );


    // generated by AI
    // return (
    //     <main className="flex items-center justify-center h-screen bg-gray-100">
    //         <div className="w-full max-w-md px-6 py-8 bg-white rounded-lg shadow-md">
    //             <div className="flex justify-center mb-6">
    //                 {/* This is where your Acme logo will go */}
    //                 {/* Replace with your actual logo component or image */}
    //                 <div className="text-blue-500">Acme</div>
    //             </div>
    //             <h2 className="text-2xl font-semibold text-center text-gray-700">Please log in to continue.</h2>

    //             <form className="mt-8 space-y-6" action="#" method="POST">
    //                 <div>
    //                     <label htmlFor="email" className="sr-only">Email</label>
    //                     <input
    //                         id="email"
    //                         name="email"
    //                         type="email"
    //                         required
    //                         className="w-full px-3 py-2 leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
    //                         placeholder="Enter your email address"
    //                     />
    //                 </div>
    //                 <div>
    //                     <label htmlFor="password" className="sr-only">Password</label>
    //                     <input
    //                         id="password"
    //                         name="password"
    //                         type="password"
    //                         required
    //                         className="w-full px-3 py-2 leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline"
    //                         placeholder="Enter password"
    //                     />
    //                 </div>
    //                 <div>
    //                     <button
    //                         type="submit"
    //                         className="w-full px-4 py-2 text-white bg-blue-500 rounded hover:bg-blue-700 focus:outline-none focus:bg-blue-700"
    //                     >
    //                         Log in
    //                     </button>
    //                 </div>
    //             </form>
    //         </div>
    //     </main>
    // );
}